### ISSUE TITLE
I smell web :> I smell collab

### ISSUE THREAD

**Issue by DarkGuy10** [BillyDoesDev/wonttellyouwhatthisis#1]
![1635372553](https://github.com/BillyDoesDev/wonttellyouwhatthisis/assets/62807269/4bcc6977-f931-4edf-aaf4-9cf2c719be73)

**Comment by BillyDoesDev** [comment]
Lmfao I wish man
Happens to be an internal thing tho

**Comment by DarkGuy10** [comment]
:< fair enough

**Comment by BillyDoesDev** [comment]
Damn, issue, no issue
Pr, no pr
Noodles, no noodles 🤧
Kung fu panda 4 trailer just dropped btw

**Comment by DarkGuy10** [comment]
Been grinding valorant all day man, istg its either Im carrying the match or getting carried, broken matchmaking
No noodles fr~
Yeah someone pinged my dc with the link, haven't watched yet tho-

**Comment by BillyDoesDev** [comment]
Damn, the valo grind 
Damn
Also yeah, graphics are pretty dope XD
